### ISSUE TITLE
The new dataset has many columns with null rows

### ISSUE THREAD

**Issue by marvinford** [DSEI21000-S21/project-tennis-ml#2]
I found many missing values in the new dataset that @vanomahi found. We have to decide whether or not we're going to use it.

**Comment by marvinford** [comment]
@vanomahi  We can use the last 10 years of the data and impute the missing values. The dataset is very comprehensive. Let's use it as the main file for our goal on the men's side. I combined the .csv files in to one file using this command` cat *.csv > atp_matches-2011-2021.csv      `

**Comment by marvinford** [comment]
@vanomahi Let's start doing some comprehensive data cleaning and EDA on this file.

**Comment by marvinford** [comment]
@vanomahi Let's look at 21 years instead of 10 for both men and women. All the files are organized and ready to be used. Here are the files for use:
```
atp_matches-2000-2021.csv
wta_matches-2000-2021.csv
```
You'll find them in their respective folders.

**Comment by vanomahi** [comment]
> @vanomahi Let's look at 21 years instead of 10 for both men and women. All the files are organized and ready to be used. Here are the files for use:
> 
> ```
> atp_matches-2000-2021.csv
> wta_matches-2000-2021.csv
> ```
> 
> You'll find them in their respective folders.

ok Thanks.

**Comment by vanomahi** [comment]
> @vanomahi Let's look at 21 years instead of 10 for both men and women. All the files are organized and ready to be used. Here are the files for use:
> 
> ```
> atp_matches-2000-2021.csv
> wta_matches-2000-2021.csv
> ```
> 
> You'll find them in their respective folders.

Perfect

**Comment by vanomahi** [comment]
> @vanomahi Let's start doing some comprehensive data cleaning and EDA on this file.

We need to agree on which columns to drop. So let's begin and then we will reconcile our data cleaning and EDA.

**Comment by vanomahi** [comment]
> @vanomahi We can use the last 10 years of the data and impute the missing values. The dataset is very comprehensive. Let's use it as the main file for our goal on the men's side. I combined the .csv files in to one file using this command`cat *.csv > atp_matches-2011-2021.csv `

Hi Marvin, I need some clarifications on this:

**Comment by vanomahi** [comment]
> > @vanomahi We can use the last 10 years of the data and impute the missing values. The dataset is very comprehensive. Let's use it as the main file for our goal on the men's side. I combined the .csv files in to one file using this command`cat *.csv > atp_matches-2011-2021.csv `
> 
> Hi Marvin, I need some clarifications on this:

It looks like you used a different dataset to do the cleaning.
